--
-- PostgreSQL database dump
--

\restrict KVJUgM2qdRN4pi8PrpgrTfbPSeEs02SEGytCxlfiyGr6MCH24fe1dRHAIDh8Y8H

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: applicant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.applicant (
    id bigint NOT NULL,
    birth_date date,
    unt_score integer NOT NULL,
    target_speciality_id character varying(20),
    user_id bigint NOT NULL
);


ALTER TABLE public.applicant OWNER TO postgres;

--
-- Name: applicant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.applicant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applicant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_deadlines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.application_deadlines (
    id integer NOT NULL,
    program_id integer,
    start_date date,
    end_date date
);


ALTER TABLE public.application_deadlines OWNER TO postgres;

--
-- Name: application_deadlines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.application_deadlines_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.application_deadlines_id_seq OWNER TO postgres;

--
-- Name: application_deadlines_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.application_deadlines_id_seq OWNED BY public.application_deadlines.id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chat_messages OWNER TO postgres;

--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: favorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    program_id character varying(20) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.favorites OWNER TO postgres;

--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: field_of_study; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.field_of_study (
    code integer CONSTRAINT op_groups_id_not_null NOT NULL,
    name character varying(255)
);


ALTER TABLE public.field_of_study OWNER TO postgres;

--
-- Name: languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.languages (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.languages OWNER TO postgres;

--
-- Name: languages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.languages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.languages_id_seq OWNER TO postgres;

--
-- Name: languages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.languages_id_seq OWNED BY public.languages.id;


--
-- Name: ntc_exam_requirements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ntc_exam_requirements (
    id integer NOT NULL,
    program_id integer,
    education_type character varying(50),
    subject1 character varying(100),
    subject2 character varying(100)
);


ALTER TABLE public.ntc_exam_requirements OWNER TO postgres;

--
-- Name: ntc_exam_requirements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ntc_exam_requirements_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ntc_exam_requirements_id_seq OWNER TO postgres;

--
-- Name: ntc_exam_requirements_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ntc_exam_requirements_id_seq OWNED BY public.ntc_exam_requirements.id;


--
-- Name: ntc_news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ntc_news (
    id integer NOT NULL,
    title character varying(255),
    content text,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ntc_news OWNER TO postgres;

--
-- Name: ntc_news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ntc_news_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ntc_news_id_seq OWNER TO postgres;

--
-- Name: ntc_news_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ntc_news_id_seq OWNED BY public.ntc_news.id;


--
-- Name: ntc_programs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ntc_programs (
    code integer CONSTRAINT ntc_programs_id_not_null NOT NULL,
    field_of_study_id integer,
    name character varying(255),
    subject_1_id integer,
    subject_2_id integer
);


ALTER TABLE public.ntc_programs OWNER TO postgres;

--
-- Name: ntc_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ntc_programs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ntc_programs_id_seq OWNER TO postgres;

--
-- Name: ntc_programs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ntc_programs_id_seq OWNED BY public.ntc_programs.code;


--
-- Name: op_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.op_groups_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.op_groups_id_seq OWNER TO postgres;

--
-- Name: op_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.op_groups_id_seq OWNED BY public.field_of_study.code;


--
-- Name: saved_programs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_programs (
    id integer NOT NULL,
    applicant_id integer,
    program_id integer
);


ALTER TABLE public.saved_programs OWNER TO postgres;

--
-- Name: saved_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.saved_programs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.saved_programs_id_seq OWNER TO postgres;

--
-- Name: saved_programs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.saved_programs_id_seq OWNED BY public.saved_programs.id;


--
-- Name: subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subject (
    id integer NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.subject OWNER TO postgres;

--
-- Name: subject_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subject_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.subject_id_seq OWNER TO postgres;

--
-- Name: subject_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.subject_id_seq OWNED BY public.subject.id;


--
-- Name: universities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.universities (
    code integer CONSTRAINT universities_id_not_null NOT NULL,
    name character varying(255),
    city character varying(100),
    address text,
    year_established integer,
    email character varying(255),
    phone character varying(20),
    passing_score integer
);


ALTER TABLE public.universities OWNER TO postgres;

--
-- Name: universities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.universities_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.universities_id_seq OWNER TO postgres;

--
-- Name: universities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.universities_id_seq OWNED BY public.universities.code;


--
-- Name: university_programs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.university_programs (
    code integer CONSTRAINT university_programs_id_not_null NOT NULL,
    university_id integer,
    ntc_program_id integer,
    local_name character varying(255),
    cost integer,
    language character varying(50),
    language_id integer
);


ALTER TABLE public.university_programs OWNER TO postgres;

--
-- Name: university_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.university_programs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.university_programs_id_seq OWNER TO postgres;

--
-- Name: university_programs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.university_programs_id_seq OWNED BY public.university_programs.code;


--
-- Name: university_staff; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.university_staff (
    id bigint NOT NULL,
    university_id character varying(20) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.university_staff OWNER TO postgres;

--
-- Name: university_staff_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.university_staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.university_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(15),
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_deadlines id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_deadlines ALTER COLUMN id SET DEFAULT nextval('public.application_deadlines_id_seq'::regclass);


--
-- Name: field_of_study code; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.field_of_study ALTER COLUMN code SET DEFAULT nextval('public.op_groups_id_seq'::regclass);


--
-- Name: languages id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages ALTER COLUMN id SET DEFAULT nextval('public.languages_id_seq'::regclass);


--
-- Name: ntc_exam_requirements id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_exam_requirements ALTER COLUMN id SET DEFAULT nextval('public.ntc_exam_requirements_id_seq'::regclass);


--
-- Name: ntc_news id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_news ALTER COLUMN id SET DEFAULT nextval('public.ntc_news_id_seq'::regclass);


--
-- Name: ntc_programs code; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_programs ALTER COLUMN code SET DEFAULT nextval('public.ntc_programs_id_seq'::regclass);


--
-- Name: saved_programs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_programs ALTER COLUMN id SET DEFAULT nextval('public.saved_programs_id_seq'::regclass);


--
-- Name: subject id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject ALTER COLUMN id SET DEFAULT nextval('public.subject_id_seq'::regclass);


--
-- Name: universities code; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.universities ALTER COLUMN code SET DEFAULT nextval('public.universities_id_seq'::regclass);


--
-- Name: university_programs code; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_programs ALTER COLUMN code SET DEFAULT nextval('public.university_programs_id_seq'::regclass);


--
-- Data for Name: applicant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.applicant (id, birth_date, unt_score, target_speciality_id, user_id) FROM stdin;
1	\N	0		3
2	2005-03-15	120	5310	4
\.


--
-- Data for Name: application_deadlines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.application_deadlines (id, program_id, start_date, end_date) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add field of study	6	add_fieldofstudy
22	Can change field of study	6	change_fieldofstudy
23	Can delete field of study	6	delete_fieldofstudy
24	Can view field of study	6	view_fieldofstudy
25	Can add ntc program	7	add_ntcprogram
26	Can change ntc program	7	change_ntcprogram
27	Can delete ntc program	7	delete_ntcprogram
28	Can view ntc program	7	view_ntcprogram
29	Can add subject	8	add_subject
30	Can change subject	8	change_subject
31	Can delete subject	8	delete_subject
32	Can view subject	8	view_subject
33	Can add university	9	add_university
34	Can change university	9	change_university
35	Can delete university	9	delete_university
36	Can view university	9	view_university
37	Can add university program	10	add_universityprogram
38	Can change university program	10	change_universityprogram
39	Can delete university program	10	delete_universityprogram
40	Can view university program	10	view_universityprogram
41	Can add user	13	add_user
42	Can change user	13	change_user
43	Can delete user	13	delete_user
44	Can view user	13	view_user
45	Can add applicant	11	add_applicant
46	Can change applicant	11	change_applicant
47	Can delete applicant	11	delete_applicant
48	Can view applicant	11	view_applicant
49	Can add university staff	12	add_universitystaff
50	Can change university staff	12	change_universitystaff
51	Can delete university staff	12	delete_universitystaff
52	Can view university staff	12	view_universitystaff
53	Can add favorite	14	add_favorite
54	Can change favorite	14	change_favorite
55	Can delete favorite	14	delete_favorite
56	Can view favorite	14	view_favorite
57	Can add university program language	15	add_universityprogramlanguage
58	Can change university program language	15	change_universityprogramlanguage
59	Can delete university program language	15	delete_universityprogramlanguage
60	Can view university program language	15	view_universityprogramlanguage
61	Can add chat message	16	add_chatmessage
62	Can change chat message	16	change_chatmessage
63	Can delete chat message	16	delete_chatmessage
64	Can view chat message	16	view_chatmessage
\.


--
-- Data for Name: chat_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_messages (id, role, content, created_at, user_id) FROM stdin;
1	user	Какие университеты есть в Астане?	2026-05-06 12:51:04.201426+05	7
2	user	Какие университеты есть в Астане?	2026-05-06 12:53:20.007592+05	7
3	assistant	В Астане находятся следующие университеты:\n\n1. Astana Medical University (проходной балл: 70)\n2. S. Seifullin Kazakh Agrotechnical University (проходной балл: 60)\n\nОба этих университета предлагают различные специальности и программы обучения. Если вы хотите получить более подробную информацию о конкретном университете или специальности, я готов помочь вам!	2026-05-06 12:53:29.401438+05	7
4	user	Где есть медицинские университеты	2026-05-06 12:56:19.330818+05	7
5	assistant	В Казахстане находятся следующие медицинские университеты:\n\n1. Astana Medical University (Астана, проходной балл: 70)\n2. Marat Ospanov West Kazakhstan Medical University (Актобе, проходной балл: 70)\n\nОба этих университета предлагают медицинские программы обучения и подготовки будущих врачей. Если вы хотите получить более подробную информацию о конкретном университете или специальности, я готов помочь вам!	2026-05-06 12:56:22.147528+05	7
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-20 11:21:10.30306+05	2	alina (APPLICANT)	1	[{"added": {}}]	13	1
2	2026-04-20 11:24:00.543931+05	2	alina (APPLICANT)	2	[{"changed": {"fields": ["First name", "Last name", "Email address", "User permissions", "Last login", "Date joined", "Phone"]}}]	13	1
3	2026-04-21 11:47:03.59439+05	1	admin (NTC_ADMIN)	2	[{"changed": {"fields": ["Role"]}}]	13	1
4	2026-04-21 15:17:07.817078+05	6104	6104 - Computer Engineering and Software	2	[{"changed": {"fields": ["Program Code"]}}]	10	1
5	2026-04-21 15:29:51.101247+05	6104	6104 - Computer Engineering and Software	2	[{"changed": {"fields": ["Program Code"]}}]	10	1
6	2026-04-21 15:37:49.171893+05	6104	6104 - Computer Engineering and Software	2	[{"changed": {"fields": ["Program Code", "Language"]}}]	10	1
7	2026-04-22 11:34:04.046017+05	6101	6101 - Computer Science	1	[{"added": {}}]	10	1
8	2026-04-22 11:53:31.288054+05	6102	6102 - Software Engineering	2	[{"changed": {"fields": ["Program Code", "Language"]}}]	10	1
9	2026-04-24 10:09:59.680608+05	6103	6103 - Big Data Analysis	1	[{"added": {}}]	10	1
10	2026-04-24 10:10:15.020774+05	6103	6103 - Big Data Analysis	2	[{"changed": {"fields": ["Program Code"]}}]	10	1
11	2026-04-24 10:22:56.614371+05	6301	6301 - Cybersecurity	1	[{"added": {}}]	10	1
12	2026-04-24 10:23:05.395965+05	6103	6103 - Big Data Analysis	2	[{"changed": {"fields": ["Program Code", "Cost of University Program"]}}]	10	1
13	2026-04-24 10:23:20.795067+05	6301	6301 - Cybersecurity	2	[{"changed": {"fields": ["Program Code", "Language"]}}]	10	1
14	2026-04-24 10:24:09.99917+05	6150	6150 - Information and communication technologies and security	2	[{"changed": {"fields": ["Program Code", "Subject 2"]}}]	7	1
15	2026-04-24 10:24:17.13979+05	6301	6301 - Cybersecurity	2	[{"changed": {"fields": ["Program Code"]}}]	10	1
16	2026-04-24 10:31:45.530656+05	4109	4109 - Business and Management	1	[{"added": {}}]	10	1
17	2026-04-24 10:34:20.595283+05	61025	61025 - Computer Systems and Software	1	[{"added": {}}]	10	1
18	2026-04-24 10:35:14.344511+05	61021	61021 - Computer Systems and Software	2	[{"changed": {"fields": ["Program Code"]}}]	10	1
19	2026-04-24 10:35:26.734771+05	61021	61021 - Computer Systems and Software	2	[{"changed": {"fields": ["Program Code"]}}]	10	1
20	2026-04-24 10:50:25.112797+05	61041	61041 - Management in IT	1	[{"added": {}}]	10	1
21	2026-04-24 11:00:53.431991+05	5	aituadmin (APPLICANT)	1	[{"added": {}}]	13	1
22	2026-04-24 11:01:30.808781+05	5	aituadmin (UNI_ADMIN)	2	[{"changed": {"fields": ["First name", "Last name", "Email address", "Role", "Phone"]}}]	13	1
23	2026-04-24 11:06:37.676481+05	5	aituadmin (UNI_ADMIN)	2	[{"added": {"name": "university staff", "object": "UniversityStaff object (1)"}}]	13	1
24	2026-05-06 12:05:23.286508+05	2	UniversityStaff object (2)	1	[{"added": {}}]	12	6
25	2026-05-06 12:59:53.392552+05	7	alu@mail.com (APPLICANT)	2	[{"changed": {"fields": ["First name", "Last name"]}}]	13	6
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	unipage	fieldofstudy
7	unipage	ntcprogram
8	unipage	subject
9	unipage	university
10	unipage	universityprogram
11	userpage	applicant
12	userpage	universitystaff
13	userpage	user
14	userpage	favorite
15	unipage	universityprogramlanguage
16	chatbot	chatmessage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	unipage	0001_initial	2026-04-20 11:09:17.077731+05
2	contenttypes	0001_initial	2026-04-20 11:09:17.103347+05
3	contenttypes	0002_remove_content_type_name	2026-04-20 11:09:17.118974+05
4	auth	0001_initial	2026-04-20 11:09:17.215883+05
5	auth	0002_alter_permission_name_max_length	2026-04-20 11:09:17.234428+05
6	auth	0003_alter_user_email_max_length	2026-04-20 11:09:17.242084+05
7	auth	0004_alter_user_username_opts	2026-04-20 11:09:17.250273+05
8	auth	0005_alter_user_last_login_null	2026-04-20 11:09:17.258707+05
9	auth	0006_require_contenttypes_0002	2026-04-20 11:09:17.261533+05
10	auth	0007_alter_validators_add_error_messages	2026-04-20 11:09:17.266957+05
11	auth	0008_alter_user_username_max_length	2026-04-20 11:09:17.271581+05
12	auth	0009_alter_user_last_name_max_length	2026-04-20 11:09:17.276717+05
13	auth	0010_alter_group_name_max_length	2026-04-20 11:09:17.285121+05
14	auth	0011_update_proxy_permissions	2026-04-20 11:09:17.293212+05
15	auth	0012_alter_user_first_name_max_length	2026-04-20 11:09:17.299026+05
16	userpage	0001_initial	2026-04-20 11:13:13.317651+05
17	admin	0001_initial	2026-04-20 11:13:13.37445+05
18	admin	0002_logentry_remove_auto_add	2026-04-20 11:13:13.385153+05
19	admin	0003_logentry_add_action_flag_choices	2026-04-20 11:13:13.393005+05
20	sessions	0001_initial	2026-04-20 11:13:13.416764+05
21	userpage	0002_alter_applicant_target_speciality	2026-04-21 12:33:10.707576+05
22	userpage	0003_favorite	2026-04-21 12:51:47.036331+05
23	unipage	0002_universityprogramlanguage	2026-04-21 15:16:30.475855+05
24	userpage	0004_alter_user_managers_remove_user_username_and_more	2026-05-06 11:51:55.755755+05
25	chatbot	0001_initial	2026-05-06 12:47:16.437347+05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
lyauljc4rvv6whz7am3d6yfeoooziu1r	.eJxVjDEOwjAMAP_iGUVNiBvTkZ03VI4d0wJqpaadEH9HlTrAene6N_S8rUO_1bL0o0IHHk6_LLM8y7QLffB0n53M07qM2e2JO2x1t1nL63q0f4OB6wAdULYgKEnFWzRCSQ17YsXA5hEthLakqJQafyG0wBKkEW3pHJkJM3y-9xk4MA:1wEhya:dD5nsAenoOhd4qkGtfkARNJ5LFU2aLzDYqEVMOQiYL8	2026-05-04 11:19:20.391989+05
gd6s11gkjiixmakgmzfsqh89b53pmo0j	.eJxVjLsOgzAMAP_FcxXVSYiBsTvfgBw7LrQVSDymqv9eITG0693p3tDzvg39vpalHxVaSHD5ZZnlWaZD6IOn--xknrZlzO5I3GlX181aXrez_RsMvA7QAteSQrDGRyLvEcUEiQsZBkYktMDq5WpG1MQKc4W1asosiimaJvh8AdqrN_w:1wKWIt:gHB3vghLhmOgfmLc3uzYFoQBOqIOI-aetNW75Z6rars	2026-05-20 12:04:19.836061+05
\.


--
-- Data for Name: favorites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.favorites (id, created_at, program_id, user_id) FROM stdin;
\.


--
-- Data for Name: field_of_study; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.field_of_study (code, name) FROM stdin;
16	Training of teachers of Kazakh language and literature
1	Pedagogy and psychology
2	Preschool education and upbringing
3	Pedagogy and methods of primary education
4	Primary military training teacher training
5	Training of physical education teachers
6	Music teacher training
7	Training of art and drawing teachers
9	Mathematics teacher training
10	Physics teacher training
11	Training of computer science teachers
12	Chemistry teacher training
13	Biology teacher training
14	Geography teacher training
15	Teacher training in humanities subjects
17	Training of teachers of Russian language and literature
18	Foreign language teacher training
20	Special pedagogy
27	Theater arts
28	Choreography
30	fine arts
31	Fashion, design
32	Philosophy and ethics
33	Religion and theology
34	Story
134	Archeology and ethnology
36	Translation business
37	Philology
40	Political science
140	International
41	Psychology
42	Journalism and reporting
43	Librarianship, information processing and archival science
44	Management and management
45	Audit and taxation
46	Finance, economics, banking and insurance
47	Marketing and advertising
49	Right
50	Biological and related sciences
51	Environment
52	Geoscience
53	Chemistry
54	Physics
55	Mathematics and Statistics
57	Information Technology
59	Communications and communication technologies
60	Chemical Engineering and Processes
61	Materials Science and Technology
62	Electrical engineering and energy
63	Electrical engineering and automation
64	Mechanics and metalworking
65	Motor vehicles
68	Food production
69	Production of materials (glass, paper, plastic, wood)
70	Textiles: clothing, footwear and leather goods
71	Mining and Mining
271	Oil and gas business
72	Pharmaceutical production technology
73	Architecture
74	Town planning, civil works and civil engineering
75	Cadastre and land management
76	Standardization, certification and metrology (by industry)
77	Crop production
78	Livestock
183	Agricultural engineering
82	Water resources and water use
83	Veterinary
90	Social work
91	Tourism
92	Leisure
93	Restaurant business and
94	Sanitary and preventive measures
95	Transport services
\.


--
-- Data for Name: languages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.languages (id, name) FROM stdin;
1	Kazakh
2	Russian
3	English
\.


--
-- Data for Name: ntc_exam_requirements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ntc_exam_requirements (id, program_id, education_type, subject1, subject2) FROM stdin;
\.


--
-- Data for Name: ntc_news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ntc_news (id, title, content, created_by, created_at) FROM stdin;
\.


--
-- Data for Name: ntc_programs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ntc_programs (code, field_of_study_id, name, subject_1_id, subject_2_id) FROM stdin;
6150	57	Information and communication technologies and security	1	14
1110	1	Pedagogy and psychology	3	4
1111	1	Practical psychology	3	4
1112	1	Psychology and mediation	3	4
1210	2	Pedagogy of preschool education and upbringing	3	4
1310	3	Pedagogy and methods of primary education	3	4
1410	4	Basic military training	13	13
1440	5	Physical culture and sports	13	13
1420	6	Music education	13	13
1450	7	Vocational training	13	13
1451	7	Labor technology and drawing	13	13
1430	7	Fine art drawing	13	13
1510	9	Mathematics	1	2
1521	9	Mathematics-Physics	1	2
1531	9	Mathematics-Informatics	1	2
1520	10	Physics	2	1
1522	10	Physics-Informatics	2	1
1530	11	Informatics	1	2
1532	11	Computer Science and Robotics	1	2
1540	12	Chemistry	5	3
1541	12	Chemistry-Biology	5	3
1550	13	Biology	3	5
1560	14	Geography	4	6
1561	14	Geography-History	4	6
6	95	Organization of transportation, movement and operation of transport	1	4
1610	15	Story	6	4
1710	16	Kazakh language and literature	8	9
1720	17	Russian language and literature	10	11
1730	18	Foreign language: two foreign languages	7	6
1910	20	Defectology	3	4
1911	20	Special pedagogy	3	4
2120	27	Directing	13	13
2130	28	Choreography	13	13
2140	30	Painting	13	13
2150	30	Graphics	13	13
2170	31	Fashion design	13	13
2171	31	Environment design	13	13
2161	31	Decorative arts	13	13
2210	32	Philosophy	6	4
2211	33	Religion and philosophy	13	13
2220	34	Story	6	4
2230	134	Archeology and ethnology	6	4
2320	36	Translation business	7	6
2330	36	Foreign philology	7	6
2331	36	Foreign philology: Uzbek language	7	6
2310	37	Philology: Kazakh language	10	11
2311	37	Philology: Russian language	10	11
3120	40	Political science	6	7
3110	140	International relations	6	7
3130	41	Psychology	3	4
3131	41	Training of psychologists-consultants in the social sphere	3	4
3220	42	Journalism	13	13
3210	43	Librarianship	10	11
3211	43	Library and pedagogical activities	10	11
4120	44	Management	1	4
4150	44	State and local government	1	4
4130	45	Accounting and audit	1	4
4110	46	Economy	1	4
4140	46	Finance	1	4
4160	47	Marketing	1	4
4161	47	IT marketing	1	4
4210	49	Jurisprudence	6	\N
4220	49	International law	6	\N
4230	49	Customs	6	\N
5110	50	Biology	3	5
5120	50	Biotechnology	3	5
5210	51	Ecology	3	4
5220	52	Geography	1	4
5320	53	Chemistry	5	3
5330	53	Examination of substances and materials in chemical engineering	5	3
5340	53	Chemical, forensic and environmental expertise	5	3
5310	54	Physics	2	1
5410	55	Mathematics	1	2
6110	57	Informatics	1	2
6111	57	Computer Science and Software Engineering	1	14
6120	57	Information systems	1	14
6121	57	Artificial Intelligence Technologies	1	14
6130	57	Computer hardware and software	1	14
6210	59	Radio engineering, electronics and telecommunications	1	2
7160	60	Chemical technology of inorganic substances	5	2
7170	60	Chemical technology of organic substances	5	2
7172	60	Oil and gas processing technology	5	2
7190	60	Chemical technology of refractory non-metallic and silicate materials	5	2
7101	61	Materials Science and	1	2
7140	62	Thermal power engineering	1	2
7150	62	Electric power industry	1	2
7151	62	Electricity supply	1	2
7152	62	Electrical Power Systems Engineering	1	2
7110	63	Automation and control	1	2
7120	64	Mechanical engineering	1	2
7121	64	Mechanical Engineering Technology	1	2
7124	64	Electrical engineering	1	2
7180	64	Technological machines and equipment	1	2
7181	64	Machinery and equipment for the oil and gas industry	1	2
7182	64	Machines and apparatus	1	2
7130	65	Transport, transport equipment and technologies	1	2
7131	65	Car service and branded	1	2
7241	68	Technology of fats and vegetable oils	3	5
7242	68	Technology of milk and dairy products	3	5
7244	68	Food technologies and catering in small and medium-sized businesses	3	5
7245	68	Technologies of meat and meat products	3	5
7250	68	Processing technology (by industry)	3	5
7252	68	Sugar technology	3	5
7280	69	Polymer production and processing technology	1	2
7230	70	Technology and design of light industry products (by area of ​​application)	1	2
7231	70	Fashion industry and distribution of light industry products	1	2
7260	70	Technology and design of textile materials	1	2
7261	70	Innovative textiles, design and decor	1	2
7210	71	Oil and gas business	1	2
7215	71	Operation and	1	2
7216	71	Exploitation of gas and oil	1	2
7220	71	Metallurgy	1	2
7211	271	Oil and gas business	\N	\N
7270	72	Pharmaceutical production technology	3	5
7310	73	Architecture	13	13
7311	73	Urban planning	13	13
7320	74	Construction	1	2
7321	74	Technology	1	2
7322	74	Construction	1	2
7330	74	Water supply,	1	2
7340	74	Production of building materials, products and structures	1	2
7088	74	Expertise and technical supervision in construction	1	2
7350	75	Land management	1	4
7360	75	Cadastre	1	4
7510	76	Standardization, certification and metrology	1	2
7513	76	Metrology	1	2
8110	77	Agronomy	3	5
8120	77	Soil science and agrochemistry	3	5
8130	77	Plant protection and quarantine	3	5
8210	78	Technology of production of livestock products	3	5
8710	183	Agricultural machinery and technology	1	2
8610	82	Water resources and water use	1	2
9111	83	Veterinary medicine	3	5
11410	90	Social work	3	4
11110	91	Tourism	4	7
11120	92	Cultural and leisure work	13	13
11121	92	Producer and technology	13	13
11124	92	Cultural and leisure activities and pop singing	13	13
11130	92	Management of vocal and choral activities	13	13
11150	92	Sports management, leisure and coaching	13	13
11141	92	Sports management, swimming and coaching	13	13
11111	93	Restaurant business and	4	7
11088	94	Management security	1	2
11310	95	Organization of transportation, movement and operation of transport	1	4
11311	95	Organization of transportation to	1	4
11312	95	Transport logistics	1	4
11210	94	Safety	1	2
\.


--
-- Data for Name: saved_programs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.saved_programs (id, applicant_id, program_id) FROM stdin;
\.


--
-- Data for Name: subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subject (id, name) FROM stdin;
3	Biology
4	Geography
1	Mathematics
2	Physics
5	Chemistry
6	World History
7	Foreign Language
8	Kazakh Language
9	Kazakh Literature
10	Russian Language
11	Russian Literature
12	Man. Society. Law
13	Creative Exam
14	Informatics
15	History of Kazakhstan
\.


--
-- Data for Name: universities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.universities (code, name, city, address, year_established, email, phone, passing_score) FROM stdin;
421	Kazakh-British Technical University (KBTU)	Almaty	59 Tole Bi str.	2001	info@kbtu.kz	+77273574242	85
1	Astana Medical University 	Astana	49/a Beybitshilik str.	1964	info@amu.kz	+77172539424	70
2	S. Seifullin Kazakh Agrotechnical University 	Astana	62 Zhenis Ave.	1957	katu_mail@kazatu.kz	+77172317547	60
3	Sh. Yessenov Caspian University of Technology and Engineering 	Aktau	34 microdistrict, building 1	1976	office@yu.edu.kz	+77292425515	50
4	Marat Ospanov West Kazakhstan Medical University 	Aktobe	68 Maresyev str.	1957	zkgmu@zkgmu.kz	+77132567210	70
5	K. Zhubanov Aktobe Regional University 	Aktobe	34 A. Moldagulova Ave.	1935	kense@zhubanov.edu.kz	+77132541244	60
6	Kurmangazy Kazakh National Conservatory 	Almaty	86 Abylai Khan Ave.	1944	info@conservatoire.kz	+77272729045	50
7	Abai Kazakh National Pedagogical University 	Almaty	13 Dostyk Ave.	1928	rector@abaiuniversity.edu.kz	+77272913366	75
8	I. Altynsarin Arkalyk Pedagogical Institute 	Arkalyk	17 Auelbekov str.	1972	api@api.edu.kz	+77143071318	50
9	S. Utebayev Atyrau University of Oil and Gas 	Atyrau	1 Baitursynov str.	1980	info@aiau.edu.kz	+77122362548	55
10	Kh. Dosmukhamedov Atyrau University 	Atyrau	212 Studentskaya str.	1950	kense@asu.edu.kz	+77122276300	50
11	S. Amanzholov East Kazakhstan University 	Oskemen	30 Kazakhstan str.	1952	kense@vku.edu.kz	+77232241458	65
12	D. Serikbayev East Kazakhstan Technical University 	Oskemen	69 Protozanov str.	1958	kense@ektu.kz	+77232267409	65
13	L.N. Gumilyov Eurasian National University 	Astana	2 Satpayev str.	1996	enu@enu.kz	+77172709500	85
14	O.A. Baikonurov Zhezkazgan University 	Zhezkazgan	7 Gurba str.	1996	zhez_un@mail.ru	+77102737633	50
15	I. Zhansugurov Zhetysu University 	Taldykorgan	187a I. Zhansugurov str.	1972	kense@zhetysu.edu.kz	+77282222123	55
16	M. Utemisov West Kazakhstan University 	Uralsk	162 Dostyk-Druzhba Ave.	1932	info@wku.edu.kz	+77112512632	55
17	T. Zhurgenov Kazakh National Academy of Arts 	Almaty	127 Panfilov str.	1978	info@kaznai.kz	+77272724398	50
18	Kazakh National University of Arts 	Astana	33 Tauelsizdik Ave.	1998	kaznua@mail.ru	+77172705499	50
19	M. Tynyshpayev Kazakh Academy of Transport and Communications 	Almaty	97 Shevchenko str.	1931	info@alt.edu.kz	+77272922115	60
20	Kazakh Academy of Sport and Tourism 	Almaty	105 Abai Ave.	1944	info@kazast.kz	+77272920215	50
21	Narxoz University	Almaty	55 Zhandosov str.	1963	info@narxoz.kz	+77273771111	75
22	International Education Corporation (IEC)	Almaty	28 Ryskulbekov str.	1980	info@mok.kz	+77272208081	65
23	Ablai Khan Kazakh University of International Relations and World Languages	Almaty	200 Muratbaev str.	1941	kazumo@ablaikhan.kz	+77272920384	80
24	Kazakh National Agrarian Research University	Almaty	8 Abay Ave.	1930	info@kaznaru.edu.kz	+77272642409	65
25	Kazakh National Women's Teacher Training University	Almaty	99 Aiteke Bi str.	1944	qyzpu@qyzpu.edu.kz	+77272331852	75
26	Asfendiyarov Kazakh National Medical University	Almaty	94 Tole Bi str.	1930	info@kaznmu.kz	+77273387090	85
27	Al-Farabi Kazakh National University	Almaty	71 Al-Farabi Ave.	1934	info@kaznu.kz	+77273773333	95
29	Satbayev University	Almaty	22 Satpaev str.	1934	info@satbayev.university	+77272926022	85
30	Karaganda Medical University	Karaganda	40 Gogol str.	1950	info@qmu.kz	+77212503930	75
31	Karaganda Buketov University	Karaganda	28 Universitetskaya str.	1938	office@buketov.edu.kz	+77212351039	65
32	Karaganda Technical University	Karaganda	56 Nursultan Nazarbayev Ave.	1953	kense@kstu.kz	+77212560328	70
33	Karaganda Industrial University	Temirtau	30 Republic Ave.	1963	kense@tttu.edu.kz	+77213915046	55
34	Korkyt Ata Kyzylorda University	Kyzylorda	29A Ayteke Bi str.	1937	kense@korkyt.kz	+77242262241	60
35	Sh. Ualikhanov Kokshetau University	Kokshetau	76 Abay str.	1962	kense@shokan.edu.kz	+77162255583	60
36	A. Baitursynov Kostanay Regional University	Kostanay	47 Baytursynov str.	1939	info@ksu.edu.kz	+77142511195	60
37	Khoja Akhmet Yassawi International Kazakh-Turkish University	Turkistan	290 B. Sattarkhanov Ave.	1991	info@ayu.edu.kz	+77253363636	75
38	Toraighyrov University	Pavlodar	64 Lomov str.	1960	info@tou.edu.kz	+77182673673	65
39	Rudny Industrial Institute	Rudny	38 50 Let Oktyabrya str.	1959	rii@rii.kz	+77143150723	50
40	Kozybayev University	Petropavlovsk	86 Pushkin str.	1937	mail@ku.edu.kz	+77152493233	60
41	Semey Medical University	Semey	103 Abay str.	1953	info@smu.edu.kz	+77222522054	70
42	Shakarim University of Semey	Semey	20A Glinka str.	1934	info@shakarim.kz	+77222313143	60
43	M.Kh. Dulaty Taraz Regional University	Taraz	7 Suleimenov str.	1958	info@tarsu.kz	+77262453663	60
44	South Kazakhstan Medical Academy	Shymkent	1 Al-Farabi square	1979	skma@skma.kz	+77252408222	70
45	M. Auezov South Kazakhstan University	Shymkent	5 Tauke Khan Ave.	1943	rector@auezov.edu.kz	+77252210141	65
47	Eurasian Humanities Institute	Astana	4 M. Zhumabayev Ave.	1995	eagi@list.ru	+77172562200	50
48	Kazakh Academy of Labor and Social Relations	Almaty	9 Nauryzbai Batyr str.	1994	info@kazatiso.kz	+77272792015	50
49	Kazakhstan Engineering and Technology University	Almaty	93A Al-Farabi Ave.	2001	info@kazetu.kz	+77273000777	50
50	Kazakh Medical University of Continuing Education	Almaty	126 Abay Ave.	1963	info@kazmuno.kz	+77273378018	65
53	Almaty Technological University	Almaty	100 Tole Bi str.	1957	rector@atu.kz	+77272935292	60
57	G. Daukeyev Almaty University of Power Engineering and Telecommunications	Almaty	126/1 Baitursynov str.	1975	aues@aues.kz	+77272925614	75
522	Astana IT University	Astana	EXPO-2017, C1 Pavilion	2019	info@astanait.edu.kz	+77172645710	90
69	University of International Business (UIB)	Almaty	8A Abay Ave.	1992	uib@uib.kz	+77272597000	70
78	L.B. Goncharov Kazakh Automobile and Road Academy	Almaty	54 Shagabutdinov str.	1991	kazdorakad@mail.ru	+77272922501	55
79	Caspian University	Almaty	521 Seifullin Ave.	1992	info@cu.edu.kz	+77272506930	65
80	Kazakh-Russian Medical University	Almaty	122 Torekulov str.	1992	krmu@krmu.kz	+77272508104	65
82	Kazakh-German University (DKU)	Almaty	173 Nazarbayev Ave.	1999	info@dku.kz	+77273550551	80
83	Almaty Management University (AlmaU)	Almaty	227 Rozybakiev str.	1988	info@almau.edu.kz	+77273133040	80
89	Kainar Academy	Almaty	7A Satpayev str.	1991	priem@kainar-u.kz	+77272558356	50
90	O.A. Dzholdasbekov Academy of Economics and Law	Taldykorgan	1 mkr., bld. 26	1997	ael_tdk@mail.ru	+77282242858	50
93	Turan University	Almaty	108 Satpayev str.	1992	turan@turan-edu.kz	+77272604000	70
103	Kazakh-Russian International University	Aktobe	52 Aiteke Bi str.	1994	kriu@kriu.kz	+77132511471	50
116	Bolashaq Academy	Karaganda	17 Abay Ave.	1995	info@kubolashak.kz	+77212420428	50
122	Karaganda University of Kazpotrebsoyuz	Karaganda	9 Akademicheskaya str.	1966	mail@keu.kz	+77212441624	60
133	Miras University	Shymkent	17 Sapabaev str.	1997	info@miras.edu.kz	+77252212356	50
140	M. Dulatov Kostanay Engineering and Economic University	Kostanay	31 Chernyshevsky str.	1996	kineu@mail.ru	+77142280248	50
141	Alikhan Bokeikhan University (ex. KazGJIU)	Semey	11 Mangilik El str.	1998	info@abu.edu.kz	+77222524855	55
146	Innovative University of Eurasia	Pavlodar	45 Lomov str.	1991	info@ineu.edu.kz	+77182314242	55
147	K. Satpayev Ekibastuz Engineering and Technical Institute	Ekibastuz	54 Energetikov str.	1994	eiti_ekibastuz@mail.ru	+77187340056	50
153	Kazakh-American Free University	Ust-Kamenogorsk	76 M. Gorkiy str.	1994	kafu@kafu.kz	+77232248500	65
154	Almaty Academy of Economics and Statistics	Almaty	25 Zhandosov str.	1998	info@aess.kz	+77273771340	50
157	Civil Aviation Academy	Almaty	44 Zakarpatskaya str.	1995	info@agakaz.kz	+77273308333	65
158	Abay Myrzakhmetov Kokshetau University	Kokshetau	189a Gorky str.	2000	info@kuam.kz	+77162254259	50
160	Eurasian Technological University	Almaty	109 Tole Bi str.	2013	info@etu.edu.kz	+77273315555	55
161	Almaty University	Almaty	24/1 Mamyr-1 dist.	1998	info@ualmaty.kz	+77273111306	50
162	Kazakh University of Ways of Communications	Almaty	82 Shevchenko str.	2000	info@kups.kz	+77272922115	50
173	Esil University (ex. KazUEFIT)	Astana	7 Zhubanov str.	2006	info@esiluniversity.edu.kz	+77172703058	60
174	M. Narikbayev KAZGUU University	Astana	8 Korgalzhyn Highway	1994	info@kazguu.kz	+77172703030	85
182	Kazakh University of Technology and Business	Astana	31 Saryarka Ave.	2003	info@kaztub.kz	+77172270101	55
184	Turan-Astana University	Astana	1 Yessenberlin str.	1998	tau_astana@mail.ru	+77172398118	60
185	Astana International University	Astana	8 Kabanbay Batyr Ave.	2018	info@aiu.edu.kz	+77172476677	70
186	Silkway International University	Shymkent	32 Tokayev str.	1992	info@swu.edu.kz	+77252951111	50
190	International IT University (IITU)	Almaty	34/1 Manas str.	2009	info@iitu.edu.kz	+77272445101	85
191	Financial Academy	Astana	25 Esenberlin str.	1965	info@finacad.kz	+77172312601	60
194	Astana University	Astana	11/1 Abay Ave.	1998	un_astana@mail.ru	+77172278030	50
195	Kazakhstan Maritime University	Aktau	1st district, bld 1/2	1996	info@kmu.edu.kz	+77292503943	50
196	South Kazakhstan State Pedagogical University	Shymkent	13 Baitursynov str.	1937	info@okgpu.edu.kz	+77252210512	70
197	Central Kazakhstan Academy	Karaganda	11 Saryarka str.	1993	info@c-k-a.kz	+77212423714	50
198	West Kazakhstan Innovative-Technological University	Uralsk	12 Ikhsanov str.	2000	info@wkitu.kz	+77112503935	50
199	Kazakhstan University of Innovative and Telecommunication Systems	Uralsk	67a K. Batyr str.	1998	kuits@list.ru	+77112513511	50
200	D. Kunayev Eurasian Law Academy	Almaty	107 Kurmangazy str.	1992	info@kunaev.kz	+77272610731	60
202	A. Kuatbekov Peoples' Friendship University	Shymkent	13 Tokayev str.	1992	info@unat.edu.kz	+77252537152	50
205	Kazakh National Academy of Choreography	Astana	9 Akmeshit str.	2016	info@balletacademy.kz	+77172790858	60
223	Taraz Innovative-Humanities University	Taraz	45 Zheltoksan str.	2008	info@tigu.kz	+77262512140	55
302	Suleyman Demirel University (SDU)	Kaskelen	1/1 Abylai Khan str.	1996	info@sdu.edu.kz	+77273079560	80
305	Bolashak Kyzylorda University	Kyzylorda	46 Abay Ave.	1998	info@bolashak-u.kz	+77242234510	50
318	Atyrau Engineering and Humanities Institute	Atyrau	212 Studentskaya str.	2001	aigi_2001@mail.ru	+77122271454	50
350	Military Institute of Land Forces	Almaty	123 Abay Ave.	1970	visv@mod.gov.kz	+77272558066	50
351	T. Bigeldinov Military Institute of Air Defense Forces	Aktobe	39 Moldagulova Ave.	1974	visvo@mod.gov.kz	+77132517511	50
353	Academy of Civil Protection (ex. Kokshetau Technical Institute)	Kokshetau	138 Auezov str.	1997	kti@emer.kz	+77162255249	50
354	M. Esbulatov Almaty Academy of the Ministry of Internal Affairs	Almaty	29 Ak-Kayik mkr.	1956	info@almacademy.kz	+77273378393	50
355	B. Beisenov Karaganda Academy of the Ministry of Internal Affairs	Karaganda	7 Ermekov str.	1969	kense@kacadem.kz	+77212303402	50
356	Sh. Kabylbayev Kostanay Academy of the Ministry of Internal Affairs	Kostanay	11 Abay Ave.	1971	kense_kost@mvd.gov.kz	+77142254422	50
357	Military Institute of the National Guard of the Republic of Kazakhstan	Petropavlovsk	290 Zhambyl str.	1997	viny@mvd.gov.kz	+77152474077	50
359	Military Engineering Institute of Radio Electronics and Communications	Almaty	126/1 Dzhandosov str.	2001	viireis@mod.gov.kz	+77273036814	50
413	Mardan Saparbayev Institute	Shymkent	34 Momyshuly Ave.	1994	msi_shymkent@mail.ru	+77252536737	50
414	Shymkent University	Shymkent	80 mkr. Sever	2001	shymkent_univer@mail.ru	+77252371101	50
416	Baishev University	Aktobe	40 Zhubanov str.	1996	info@bu.edu.kz	+77132512145	55
419	University of Foreign Languages and Professional Career	Almaty	17 Kazybek Bi str.	2004	info@inyaz-career.kz	+77272912555	50
501	Zhangir Khan West Kazakhstan Agricultural-Technical University	Uralsk	51 Zhangir Khan str.	1963	wkau@wkau.kz	+77112506041	60
503	Nur-Mubarak Egyptian University of Islamic Culture	Almaty	73 Al-Farabi Ave.	2001	info@nmu.kz	+77273020930	50
517	Pavlodar Pedagogical University	Pavlodar	60 Mira str.	1962	ppu@ppu.edu.kz	+77182554722	75
518	Academy of the Border Service of the NSC RK	Almaty	103 Dostyk Ave.	1931	pogranacademy@knb.gov.kz	+77272635601	50
979	KIMEP University	Almaty	2 Abay Ave.	1992	info@kimep.kz	+77272704213	90
\.


--
-- Data for Name: university_programs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.university_programs (code, university_id, ntc_program_id, local_name, cost, language, language_id) FROM stdin;
6104	13	6111	Computer Engineering and Software	1600000	Russian, Kazakh	2
6101	522	6111	Computer Science	2500000	\N	3
6102	522	6150	Software Engineering	2500000	English	3
6103	522	6121	Big Data Analysis	2500000	\N	3
6301	522	6150	Cybersecurity	2500000	\N	3
4109	421	4120	Business and Management	1700000	\N	3
61025	421	6111	Computer Systems and Software	2000000	\N	3
61021	421	6111	Computer Systems and Software	2000000	\N	3
61041	421	6150	Management in IT	1700000	\N	3
\.


--
-- Data for Name: university_staff; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.university_staff (id, university_id, user_id) FROM stdin;
1	522	5
2	1	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, last_login, is_superuser, first_name, last_name, email, is_staff, is_active, date_joined, role, phone, created_at) FROM stdin;
2	pbkdf2_sha256$1200000$3Sr9JFmmRc5ivfJBzP2Nsh$qmocSDp1rUg2DYQS/TDY5WwA+sdjNLg5LotPRBIQ+Cc=	2026-04-20 11:23:26+05	f	Алина	Бигалиева	alina@bilimge.kz	f	t	2026-04-20 11:23:42+05	APPLICANT	+77007841234	2026-04-20 11:21:10.301193+05
3	pbkdf2_sha256$1200000$PRu2tTNvJvyJp6DvU6NJUe$dVp612SJZa2aArjhNsv42DbAFcHlAsZ56hAV9+/Oabk=	\N	f			z@mail.com	f	t	2026-04-21 11:24:58.333089+05	APPLICANT		2026-04-21 11:24:59.486795+05
1	pbkdf2_sha256$1200000$8NTXEVLZAeEmrs5wl4GHc0$bJwMsc8CXlOjCqJIz45FdLw0AM5by/OdMCfhTkYJfgc=	2026-04-20 11:19:20+05	t			admin@gmail.com	t	t	2026-04-20 11:17:10+05	NTC_ADMIN	\N	2026-04-20 11:17:11.446939+05
4	pbkdf2_sha256$1200000$yjgNgVsBuVcOtX1QnnYhq6$gGcR/ZH07U3ToeZom86wuH305ZqYyW74EzgtIMt5pgY=	\N	f	Appli	Last	a@mail.com	f	t	2026-04-21 12:36:09.770615+05	APPLICANT	87052346517	2026-04-21 12:36:11.108676+05
5	pbkdf2_sha256$1200000$wtr2ilp8gT43qvz9VWhVVj$N8ewdZ6dr4m03uis5Td4DiAYa0PYvFaONNKl3sPd0MM=	\N	f	Aitair	Bubilu	info@astanait.edu.kz	f	t	2026-04-24 11:00:52+05	UNI_ADMIN	+77172645716	2026-04-24 11:00:53.427973+05
6	pbkdf2_sha256$1200000$TAIjmjht0ESr7UjWzK0jDn$BZCNRPYigmVowZoedms/K99SXUDSrn/k9jEnIAh6+aI=	2026-05-06 12:04:19.829711+05	t			bz@gmail.com	t	t	2026-05-06 12:03:49.691459+05	SUPER_ADMIN	\N	2026-05-06 12:03:50.271757+05
7	pbkdf2_sha256$1200000$6u1BWWE7T5uN5BHwflV7HV$MTyhS64sZ92N+Fex1XiZhJo7bDfEr5aJc+nGuDA/dec=	\N	f	Алуа	Бекетова	alu@mail.com	f	t	2026-05-06 12:07:34.779555+05	APPLICANT	\N	2026-05-06 12:07:36.193069+05
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	48
\.


--
-- Name: applicant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.applicant_id_seq', 2, true);


--
-- Name: application_deadlines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.application_deadlines_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_messages_id_seq', 5, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 25, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: favorites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.favorites_id_seq', 1, false);


--
-- Name: languages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.languages_id_seq', 3, true);


--
-- Name: ntc_exam_requirements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ntc_exam_requirements_id_seq', 1, false);


--
-- Name: ntc_news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ntc_news_id_seq', 1, false);


--
-- Name: ntc_programs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ntc_programs_id_seq', 1, true);


--
-- Name: op_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.op_groups_id_seq', 1, false);


--
-- Name: saved_programs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.saved_programs_id_seq', 1, false);


--
-- Name: subject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subject_id_seq', 15, true);


--
-- Name: universities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.universities_id_seq', 1, false);


--
-- Name: university_programs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.university_programs_id_seq', 1, false);


--
-- Name: university_staff_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.university_staff_id_seq', 2, true);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, true);


--
-- Name: applicant applicant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applicant
    ADD CONSTRAINT applicant_pkey PRIMARY KEY (id);


--
-- Name: applicant applicant_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applicant
    ADD CONSTRAINT applicant_user_id_key UNIQUE (user_id);


--
-- Name: application_deadlines application_deadlines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_deadlines
    ADD CONSTRAINT application_deadlines_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_user_id_program_id_e1bdad25_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_user_id_program_id_e1bdad25_uniq UNIQUE (user_id, program_id);


--
-- Name: languages languages_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_name_key UNIQUE (name);


--
-- Name: languages languages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pkey PRIMARY KEY (id);


--
-- Name: ntc_exam_requirements ntc_exam_requirements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_exam_requirements
    ADD CONSTRAINT ntc_exam_requirements_pkey PRIMARY KEY (id);


--
-- Name: ntc_news ntc_news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_news
    ADD CONSTRAINT ntc_news_pkey PRIMARY KEY (id);


--
-- Name: ntc_programs ntc_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_programs
    ADD CONSTRAINT ntc_programs_pkey PRIMARY KEY (code);


--
-- Name: field_of_study op_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.field_of_study
    ADD CONSTRAINT op_groups_pkey PRIMARY KEY (code);


--
-- Name: saved_programs saved_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_programs
    ADD CONSTRAINT saved_programs_pkey PRIMARY KEY (id);


--
-- Name: subject subject_name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_name_unique UNIQUE (name);


--
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- Name: universities universities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_pkey PRIMARY KEY (code);


--
-- Name: university_programs university_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_programs
    ADD CONSTRAINT university_programs_pkey PRIMARY KEY (code);


--
-- Name: university_staff university_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_staff
    ADD CONSTRAINT university_staff_pkey PRIMARY KEY (id);


--
-- Name: university_staff university_staff_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_staff
    ADD CONSTRAINT university_staff_user_id_key UNIQUE (user_id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: applicant_target_speciality_id_a00e6ee8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX applicant_target_speciality_id_a00e6ee8 ON public.applicant USING btree (target_speciality_id);


--
-- Name: applicant_target_speciality_id_a00e6ee8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX applicant_target_speciality_id_a00e6ee8_like ON public.applicant USING btree (target_speciality_id varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: chat_messages_user_id_cf3eadd8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX chat_messages_user_id_cf3eadd8 ON public.chat_messages USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: favorites_program_id_12467995; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX favorites_program_id_12467995 ON public.favorites USING btree (program_id);


--
-- Name: favorites_program_id_12467995_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX favorites_program_id_12467995_like ON public.favorites USING btree (program_id varchar_pattern_ops);


--
-- Name: favorites_user_id_d60eb79f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX favorites_user_id_d60eb79f ON public.favorites USING btree (user_id);


--
-- Name: university_staff_university_id_a56c50a0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX university_staff_university_id_a56c50a0 ON public.university_staff USING btree (university_id);


--
-- Name: university_staff_university_id_a56c50a0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX university_staff_university_id_a56c50a0_like ON public.university_staff USING btree (university_id varchar_pattern_ops);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: applicant applicant_user_id_045d27f2_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applicant
    ADD CONSTRAINT applicant_user_id_045d27f2_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: application_deadlines application_deadlines_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_deadlines
    ADD CONSTRAINT application_deadlines_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.university_programs(code) ON DELETE CASCADE;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_messages chat_messages_user_id_cf3eadd8_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_user_id_cf3eadd8_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: favorites favorites_user_id_d60eb79f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_user_id_d60eb79f_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ntc_programs fk_ntc_subject_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_programs
    ADD CONSTRAINT fk_ntc_subject_1 FOREIGN KEY (subject_1_id) REFERENCES public.subject(id) ON DELETE SET NULL;


--
-- Name: ntc_programs fk_ntc_subject_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_programs
    ADD CONSTRAINT fk_ntc_subject_2 FOREIGN KEY (subject_2_id) REFERENCES public.subject(id) ON DELETE SET NULL;


--
-- Name: ntc_exam_requirements ntc_exam_requirements_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_exam_requirements
    ADD CONSTRAINT ntc_exam_requirements_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.ntc_programs(code) ON DELETE CASCADE;


--
-- Name: ntc_programs ntc_programs_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ntc_programs
    ADD CONSTRAINT ntc_programs_group_id_fkey FOREIGN KEY (field_of_study_id) REFERENCES public.field_of_study(code) ON DELETE CASCADE;


--
-- Name: saved_programs saved_programs_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_programs
    ADD CONSTRAINT saved_programs_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.university_programs(code) ON DELETE CASCADE;


--
-- Name: university_programs university_programs_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_programs
    ADD CONSTRAINT university_programs_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- Name: university_programs university_programs_ntc_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_programs
    ADD CONSTRAINT university_programs_ntc_program_id_fkey FOREIGN KEY (ntc_program_id) REFERENCES public.ntc_programs(code) ON DELETE SET NULL;


--
-- Name: university_programs university_programs_university_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_programs
    ADD CONSTRAINT university_programs_university_id_fkey FOREIGN KEY (university_id) REFERENCES public.universities(code) ON DELETE CASCADE;


--
-- Name: university_staff university_staff_user_id_24d53757_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.university_staff
    ADD CONSTRAINT university_staff_user_id_24d53757_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict KVJUgM2qdRN4pi8PrpgrTfbPSeEs02SEGytCxlfiyGr6MCH24fe1dRHAIDh8Y8H

