# Generated by Django 6.0.3 on 2026-03-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name='University Code')),
                ('name', models.CharField(verbose_name='University Name')),
                ('city', models.CharField(verbose_name='City')),
                ('address', models.CharField(verbose_name='University Address')),
                ('year_established', models.IntegerField(verbose_name='Year Established')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(verbose_name='Phone Number')),
            ],
            options={
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='University_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name='Code')),
                ('local_name', models.CharField(verbose_name='Name of University Program')),
                ('cost', models.IntegerField(verbose_name='Cost of University Program')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='unipage.university')),
            ],
            options={
                'db_table': 'university_programs',
            },
        ),
    ]
