# Generated by Django 6.0.3 on 2026-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Code of Field of Study')),
                ('name', models.CharField(max_length=255, verbose_name='Naming of Field of Study')),
            ],
            options={
                'db_table': 'field_of_study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NtcProgram',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Program Code')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ntc_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Subject Name')),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='University Code')),
                ('name', models.CharField(max_length=255, verbose_name='University Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='University Address')),
                ('year_established', models.IntegerField(verbose_name='Year Established')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('passing_score', models.IntegerField(verbose_name='Passing Score')),
            ],
            options={
                'db_table': 'universities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Program Code')),
                ('local_name', models.CharField(max_length=255, verbose_name='Name of University Program')),
                ('cost', models.IntegerField(verbose_name='Cost of University Program')),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'university_programs',
                'managed': False,
            },
        ),
    ]
