# Generated by Django 6.0.3 on 2026-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Code of Field of Study')),
                ('name', models.CharField(max_length=255, verbose_name='Naming of Field of Study')),
            ],
            options={
                'db_table': 'field_of_study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NtcProgram',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Program Code')),
                ('name', models.CharField(max_length=255)),
                ('subject_1', models.CharField(max_length=255)),
                ('subject_2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ntc_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Program Code')),
                ('local_name', models.CharField(max_length=255, verbose_name='Name of University Program')),
                ('cost', models.IntegerField(verbose_name='Cost of University Program')),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'university_programs',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='University_program',
        ),
    ]
