# Generated by Django 6.0.3 on 2026-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipage', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMobility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_university_name', models.CharField(max_length=255, verbose_name='Partner University')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
            options={
                'db_table': 'academic_mobility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Exam Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Exam Description')),
            ],
            options={
                'db_table': 'entrance_exams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntranceRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Requirement Description')),
            ],
            options={
                'db_table': 'entrance_requirements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'university_languages',
                'managed': False,
            },
        ),
    ]
