# Generated by Django 6.0.3 on 2026-05-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipage', '0006_ntcprogram_minimum_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Accreditation Name')),
                ('issued_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Issued By')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
            ],
            options={
                'db_table': 'accreditations',
                'managed': False,
            },
        ),
    ]
