# Generated by Django 6.0.3 on 2026-04-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipage', '0001_initial'),
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='target_speciality',
            field=models.ForeignKey(blank=True, db_column='target_speciality_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='unipage.ntcprogram'),
        ),
    ]
