# Generated by Django 6.0.3 on 2026-05-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipage', '0007_accreditation'),
        ('userpage', '0005_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='target_speciality',
        ),
        migrations.AddField(
            model_name='applicant',
            name='subject_1',
            field=models.ForeignKey(blank=True, db_column='subject_1_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants_subject_1', to='unipage.subject'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='subject_2',
            field=models.ForeignKey(blank=True, db_column='subject_2_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants_subject_2', to='unipage.subject'),
        ),
    ]
