# Generated by Django 6.0.3 on 2026-05-16 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipage', '0010_universityprogram_cost'),
        ('userpage', '0006_remove_applicant_target_speciality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(db_column='university_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='unipage.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_universities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_universities',
                'unique_together': {('user', 'university')},
            },
        ),
    ]
