# Generated by Django 6.0.3 on 2026-05-13 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikt', models.CharField(max_length=20, verbose_name='ИКТ')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('score', models.IntegerField(verbose_name='Сумма баллов')),
                ('university_code', models.CharField(max_length=20, verbose_name='Код ОВПО')),
                ('field_code', models.CharField(max_length=20, verbose_name='Код специальности')),
                ('field_name', models.CharField(max_length=255, verbose_name='Специальность')),
                ('year', models.IntegerField(default=2025, verbose_name='Учебный год')),
            ],
            options={
                'db_table': 'grant_winners',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author_type', models.CharField(choices=[('ntc', 'NTC'), ('university', 'University')], max_length=20)),
                ('university_id', models.IntegerField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
