# Generated by Django 6.0.3 on 2026-05-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Image URL'),
        ),
    ]
